apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: "{{ .scyllaDBMonitoringName }}"
spec:
  baseImage: "docker.io/grafana/grafana:8.4.0"
  client:
    preferService: true
  ingress:
    enabled: True
    pathType: Prefix
    path: "/"
  config:
    log:
      mode: "console"
      level: "error"
    log.frontend:
      enabled: true
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
    security:
      admin_password: "admin"
      admin_user: "admin"
  service:
    name: "grafana-service"
    labels:
      app: "grafana"
      type: "grafana-service"
  dashboardLabelSelector:
  - matchExpressions:
    - key: app
      operator: In
      values:
      - grafana
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
