apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: "{{ .scyllaDBMonitoringName }}-prometheus"
spec:
  name: prometheus.yaml
  datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: "http://{{ .scyllaDBMonitoringName }}-prometheus:9090" # FIXME: move to https
    isDefault: true
    version: 1
    editable: true
    jsonData:
      tlsSkipVerify: true # FIXME: remove
      timeInterval: "5s"
