apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .scyllaDBMonitoringName }}-prometheus"
  annotations:
    {{- .ingressAnnotations | toYAML | nindent 4 }}
spec:
  ingressClassName: {{ or .ingressClassName "null" }}
  rules:
  {{- range $_, $dnsDomain := .dnsDomains }}
  - host: "{{ $dnsDomain }}"
    http:
      paths:
      - backend:
          service:
            name: "{{ $.scyllaDBMonitoringName }}-prometheus"
            port:
              number: 9090
        path: /
        pathType: Prefix
  {{- end }}
