apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name:  "{{ .scyllaDBMonitoringName }}"
  labels:
    scylladbmonitoring-name: "{{ .scyllaDBMonitoringName }}"
spec:
  groups:
  - name: ./example.rules
    rules:
    - alert: ExampleAlert
      expr: vector(1)

