apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: "{{ .scyllaDBMonitoringName }}"
spec:
  serviceAccountName: "{{ .scyllaDBMonitoringName }}-prometheus"
  web:
    pageTitle: "ScyllaDB Prometheus"
    tlsConfig:
      cert:
        secret:
          name: "{{ .scyllaDBMonitoringName }}-prometheus-serving-certs"
          key: "tls.crt"
      keySecret:
        name: "{{ .scyllaDBMonitoringName }}-prometheus-serving-certs"
        key: "tls.key"
#      clientAuthType: "RequireAndVerifyClientCert"
      client_ca:
        configMap:
          name: "{{ .scyllaDBMonitoringName }}-prometheus-client-ca"
          key: "ca-bundle.crt"
    httpConfig:
      http2: true
  serviceMonitorSelector:
    matchLabels: {}
  resources:
    requests:
      memory: 400Mi
  alerting:
    alertmanagers:
    - namespace: "{{ .namespace }}"
      name: "{{ .scyllaDBMonitoringName }}"
      port: web
  ruleSelector:
    matchLabels:
      scylla-operator.scylladb.com/scylladbmonitoring-name: "{{ .scyllaDBMonitoringName }}"
  {{- if .volumeClaimTemplate }}
  storage:
    volumeClaimTemplate:
      {{- .volumeClaimTemplate | toYAML | nindent 6 }}
  {{- end }}
