apiVersion: v1
kind: Service
metadata:
  name: "{{ .scylladbMonitoringName }}-prometheus"
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    scylla-operator.scylladb.com/scylladbmonitoring-name: "{{ .scylladbMonitoringName }}"
