apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: "{{ .scyllaDBMonitoringName }}"
spec:
  serviceAccountName: "{{ .scyllaDBMonitoringName }}-prometheus"
  serviceMonitorSelector:
    matchLabels: {}
  resources:
    requests:
      memory: 400Mi
  alerting:
    alertmanagers:
    - namespace: "{{ .namespace }}"
      name: "{{ .scyllaDBMonitoringName }}"
      port: web
  ruleSelector:
    matchLabels:
      scylla-operator.scylladb.com/scylladbmonitoring-name: "{{ .scyllaDBMonitoringName }}"
  {{- if .volumeClaimTemplate }}
  storage:
    volumeClaimTemplate:
      {{- .volumeClaimTemplate | toYAML | nindent 6 }}
  {{- end }}
