{{- if gt (int .Values.replicas) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scylla-operator
  namespace: scylla-operator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "scylla-operator.selectorLabels" . | nindent 6 }}
{{- end }}
