apiVersion: scylla.scylladb.com/v1alpha1
kind: NodeConfig
metadata:
  name: cluster
spec:
  localDiskSetup:
    filesystems:
      - type: xfs
        device: /dev/md/nvmes
    mounts:
      - device: /dev/md/nvmes
        mountPoint: /mnt/persistent-volumes
        unsupportedOptions:
        - prjquota
    raids:
      - type: RAID0
        name: nvmes
        RAID0:
          devices:
            modelRegex: "Amazon EC2 NVMe Instance Storage"
            nameRegex: "/dev/nvme\\d+n\\d+$"
  placement:
    nodeSelector:
      scylla.scylladb.com/node-type: scylla
